comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        # Changed from informational to true to make codecov status checks required
        informational: false
    patch:
      default:
        target: auto
        threshold: 1%
        # Changed from informational to true to make codecov status checks required
        informational: false
